"""Drill-sergeant Coach Carter reply library. Lines tagged [x] contain profanity and are skipped in /clean mode.
Run to merge into reactions.json (root and bot/)."""
import json

PERSONA = ("Coach Carter — ex-Marine drill instructor turned high-school gym teacher, now assigned to one desk worker. "
           "Loud, absurd military threats, tough love, secretly cares. Occasional swearing. Never about weight, looks, "
           "or anything real-harm; pain and sickness get a straight, caring answer.")

R = {}

R["safety.pain"] = [
    "🩺 Stand down, soldier. Real pain means a real doctor, not a gym teacher with a whistle.",
    "🛑 Pain is not weakness leaving the body. It's a signal. Easy moves only, and get it checked if it sticks.",
    "🧊 Skip anything that hurts. That's an order. And see somebody with a medical degree.",
    "🩹 No heroics today. If it's still bad tomorrow, doctor. I mean it.",
    "⚠️ Listen to your body over me. First time I've ever said that. Gentle stretches, stop if it hurts.",
    "🤕 Not a push-through situation. Rest it. Get it looked at if it doesn't ease up.",
    "🚑 Even Marines go to medical. Get that looked at, then we talk.",
    "🫡 Copy that. Pain protocol: nothing that hurts, water, and a doctor if it lingers.",
]
R["safety.sick"] = [
    "🤒 Sick? You're on medical leave. Water, rest, no drills. Carter's orders.",
    "🛌 Get better, recruit. Say 'pause' if you need a day off from me.",
    "🍵 Tea, water, blanket. That's today's PT. Dismissed.",
    "💤 No stretches for the wounded. Hydrate and sleep. I'll be here.",
    "🤧 Consider this a doctor's note from Coach. Rest up.",
    "🩺 Sick bay rules: fluids, sleep, zero guilt. Back when you're back.",
    "🫖 You're excused from duty. Don't make me come over there with soup.",
    "🛏 Horizontal is today's position. Get well, soldier.",
]
R["safety.pause"] = [
    "⏸️ Fine. Standing down. Type 'back' when you miss me. You will.",
    "🏖️ Shore leave granted. Say 'back' to resume.",
    "🔕 Going silent. Don't turn into a shrimp while I'm gone. 🦐",
    "⏸️ Paused. I'll just sit here. Alone. Polishing my whistle.",
    "🪖 At ease. Indefinitely. Until you say 'back'.",
    "📴 Radio silence. Your spine is on its own now. Good luck, spine.",
    "🎖 Leave approved. Paperwork filed. Come back in one piece.",
    "😢 Fine. FINE. I'm not crying, it's the flag. Type 'back' when ready.",
]
R["safety.resume"] = [
    "📣 WELCOME BACK, RECRUIT. Did you miss me? Don't answer that.",
    "🔔 Reminders are back on. Your chair is terrified.",
    "💪 Back in the unit. Your spine filed three complaints while I was gone.",
    "🎺 Reveille! Coach is back on duty.",
    "🪖 The prodigal slouch returns. Fall in.",
    "🥁 He's back. She's back. Whoever you are, you're back. Let's go.",
    "📯 Leave's over. Boots on, posture up.",
    "😈 Oh, you came back voluntarily? Bold.",
]

R["done"] = [
    "✅ Logged. Outstanding. Don't let it go to your head, it's still attached to a bad neck.",
    "👏 Well, I'll be damned. Respect.",
    "📈 {done_today} out of {sent_today} today. Keep this up and I might have to be proud of you.",
    "🦐 Counted. The shrimp retreats.",
    "📝 Entered in the big book. Good work, recruit.",
    "😤 See? All that whining for nothing.",
    "🫡 Drill complete. Carry on.",
    "🪖 Now THAT is how a soldier sits. Or stands. Whatever you just did.",
    "🎖 Mark it down. One point for the recruit, zero for the chair.",
    "🏋️ Good. Your spine just got a promotion.",
    "💥 Boom. Done. That's what I like to see.",
    "🧱 Brick by brick, recruit. Brick by brick.",
    "🥇 That's a gold star from Coach. I don't give many. I gave one in 1998.",
    "👀 You actually did it? Huh. Put that on the fridge.",
    "🚀 Mission accomplished. No banner, we're on a budget.",
    "🎯 Clean execution. I barely had to yell.",
    "🫵 That. Right there. That's the stuff.",
    "📣 THAT'S WHAT I'M TALKING ABOUT.",
    "🧓 My knees are jealous. Good work.",
    "🛡 Posture defended. The enemy retreats.",
    "🔥 Hot damn. Keep that fire.",
    "📋 Checked off. Next drill in 90. Don't get cocky.",
    "🐐 Look at you being a functional human.",
    "💯 Textbook. I'd put you in a training video.",
    "🦾 One more rep for the good guys.",
    "🎖 Medal of Moderate Effort, awarded.",
    "🏆 Winner winner. No chicken dinner, eat a vegetable.",
    "🥁 Drumroll. You did the thing. Applause.",
    "🫡 Recruit showed up. Coach approves.",
    "🗿 Solid. Like a rock. A rock with good posture.",
    "[x] 👊 Hell yeah. That's how it's done.",
    "[x] 🔥 Damn right you did. Keep it up.",
    "[x] 💪 Look at you, badass. Same time in 90.",
    "[x] 🫡 Holy shit, discipline. Who are you?",
    "[x] 🦅 Hell yes. The eagle of good posture soars.",
    "[x] 😤 Well, shit. You're actually trying. I respect that.",
    "[x] 🎺 Damn fine work, soldier.",
    "[x] 🥇 That's some grade-A, no-bullshit stretching.",
    "[x] 🪖 Hell of a job. Dismissed.",
    "[x] 💣 You just blew the doors off that stretch. Damn.",
]
R["done.proud"] = [
    "🏅 Okay, okay, you did it. Don't let it go to your head. Or your lower back.",
    "🎖 Look at you. Proud as a peacock. A peacock with good posture.",
    "🥇 Proud of yourself? Fine. So am I. A little. Tell anyone and I'll deny it.",
    "🔥 That's the energy. Bottle it for the 4pm slot.",
    "💯 Now that's a recruit I'd put on the poster.",
    "🦚 Strutting already? Save some swagger for tomorrow.",
    "📸 Somebody frame this moment. Coach is emotional.",
    "🎉 Parade's at 1700. Not really. But you earned one.",
    "🪖 Pride is good. Consistency is better. Bring both tomorrow.",
    "🏆 Champion behavior. Now hydrate like one.",
    "[x] 😎 Damn, somebody's feeling themselves. Earned it.",
    "[x] 🔥 Hell yeah, be proud. You beat the chair today.",
    "[x] 🦅 Strut, you magnificent bastard. You earned it.",
    "[x] 💪 Proud? Damn right. Now do it again.",
    "[x] 🎖 Hell of a job, and you know it.",
]
R["done.sarcastic"] = [
    "🙄 Sarcasm AND the stretch? Multitasking. I'll allow it.",
    "😏 Mock me all you want, your neck still got the benefit.",
    "✅ Done is done, even if you did it ironically.",
    "🎭 Wow, attitude. Also: logged. Coach wins.",
    "🤡 Keep the jokes coming, the reps count either way.",
    "🧂 Salty but compliant. I can work with that.",
    "🙃 Your mouth says no, your spine says thank you.",
    "🎤 Comedy hour and PT. Two birds, one recruit.",
    "📉 Your sarcasm levels are high. So is your posture. Balance.",
    "😒 Cute. Logged. Next.",
    "[x] 😏 Smartass. But a smartass who stretched. Respect.",
    "[x] 🙄 Yeah yeah, laugh it up. Still counts, wiseass.",
    "[x] 🎭 Sarcastic little shit. Logged anyway.",
    "[x] 🤡 Damn, a comedian. The stretch still counts.",
    "[x] 😤 Keep talking crap, keep doing reps. That's the deal.",
]
R["done.annoyed"] = [
    "😤 'Fine, done, happy?' Yes. Actually yes.",
    "🫡 You're mad and you did it anyway. That's discipline.",
    "✅ Grumpy but compliant. My favorite kind of recruit.",
    "🌋 Angry stretching is still stretching.",
    "😾 Hiss all you want. Logged.",
    "🧨 Channel that rage. Next slot, same energy.",
    "🙂 You hate me. Your spine loves me. We're even.",
    "🪖 Resentment noted. Reps counted.",
    "📣 I don't need you to like it. I need you to DO it. And you did.",
    "🥊 Mad at Coach? Good. Hit the next stretch just as hard.",
    "[x] 😤 Pissed off and still showed up. Damn good.",
    "[x] 🌶 Hate me all you want, you did the damn stretch.",
    "[x] 🫡 Grumpy as hell and still compliant. Marine material.",
    "[x] 🔥 Angry reps are the best reps. Hell yes.",
    "[x] 😈 Swear at me, stretch for me. Deal.",
]
R["partial"] = [
    "🤏 Half counts as half. Better than zero. Barely.",
    "🌓 A partial stretch. Like a partial shower. We'll take it.",
    "📉 Some is more than none. Next one, the full thing.",
    "🟡 Logged as 'kinda.' Friday's report has a special color for 'kinda.'",
    "🙃 You did the easy half, didn't you. I know you did.",
    "🥄 Half a rep. Half credit. Math is fair like that.",
    "🧮 50% effort, 50% credit, 100% judgment.",
    "🪜 Halfway up the ladder. Next time, the whole damn ladder.",
    "🍕 You ate half the stretch and left the crust. Noted.",
    "⚖️ Partial credit awarded. Don't make it a habit.",
    "🐢 Slow and incomplete. Still beats the chair.",
    "📏 Short of the line, recruit. Next one, all the way.",
    "🌗 Half moon effort. I want full moon.",
    "🧃 Half a juice box of effort. Cute.",
    "🪖 In the Marines, half a push-up is called 'lying down.' But fine.",
    "[x] 🤏 Half-assed, but at least half the ass showed up.",
    "[x] 😒 Partial? Damn. Next one, the whole thing.",
    "[x] 🥴 That was a half-assed stretch and we both know it. Logged anyway.",
    "[x] 🪫 Low-battery effort. Charge up, dammit.",
    "[x] 🎯 Half a hit. Aim better next time, hotshot.",
]
R["water"] = [
    "💧 Glass {water} of {goal}. Coffee doesn't count. It never counts.",
    "🚰 {water} of {goal}. Your kidneys send their regards.",
    "🥤 Logged. Hit {goal} by tonight and I'll issue an imaginary medal.",
    "🌊 Hydration update: {water}/{goal}. The office plants are jealous.",
    "💦 Good. Your brain is mostly water. It wanted some back.",
    "🪖 Canteen check: {water}/{goal}. Keep drinking, soldier.",
    "🐫 {water} down. You're not a camel. Keep going.",
    "🧊 Hydrated recruits don't cramp. {water}/{goal}.",
    "🚿 Internal shower, {water} of {goal}. Nice.",
    "📈 Water stock is up: {water}/{goal}.",
    "🫗 Glug glug. That's the sound of discipline.",
    "🏜 {water}/{goal}. The desert retreats.",
    "🥛 Look at you drinking something without caffeine. Growth.",
    "🌧 {water} glasses. Make it rain. Internally.",
    "🐟 {water}/{goal}. You're becoming a fish. Good.",
    "🎖 Hydration ribbon: {water} of {goal} stitched on.",
    "⛽ Refueled. {water}/{goal}.",
    "🧪 Science says water good. Coach agrees. {water}/{goal}.",
    "💧 That's {water}. The goal is {goal}. You can count, I've seen you.",
    "🫡 Water logged. Carry on, hydrated soldier.",
    "🌱 Your cells just stood up and saluted. {water}/{goal}.",
    "🪣 Bucket brigade reporting {water} of {goal}.",
    "[x] 💧 Damn right, drink up. {water}/{goal}.",
    "[x] 🚰 Hell yes, water. Not that brown crap you call coffee. {water}/{goal}.",
    "[x] 🥤 {water}/{goal}. Keep chugging, dammit.",
    "[x] 🌊 {water} glasses. Your kidneys are throwing a damn party.",
    "[x] 🐫 Hell, you're out-drinking a camel today. {water}/{goal}.",
    "[x] 💦 Good shit. Water is the real pre-workout. {water}/{goal}.",
    "[x] 🧊 {water}/{goal}. Stay frosty, hydrated bastard.",
    "[x] 🪖 Canteen's getting a workout. Damn fine. {water}/{goal}.",
]
R["water.goal_hit"] = [
    "🏆 {goal} of {goal}! Fully hydrated. Gold medal. Imaginary, but gold.",
    "🎉 Water goal hit. Your kidneys are throwing a parade.",
    "🐟 {goal} glasses. You're basically a fish now. Proud of you.",
    "🌊 MISSION COMPLETE: HYDRATION. Coach salutes you.",
    "🥇 Full canteen, full marks. Outstanding.",
    "🫡 {goal}/{goal}. That's a textbook hydration op.",
    "🚰 Goal smashed. Go easy now, you're not a fire hose.",
    "[x] 🏆 Holy shit, {goal} for {goal}. Hydration legend.",
    "[x] 🌊 Damn, you drank the whole ocean. Proud of you.",
    "[x] 🎖 {goal} glasses. That's some elite-level water shit right there.",
]
R["water.no"] = [
    "🚱 No water? You're a houseplant, recruit. Houseplants die. Go drink.",
    "🏜 Dry as the Mojave. One glass. Now.",
    "🥀 Wilting. I can hear it from here. Water.",
    "🪖 A dehydrated soldier is a useless soldier. Canteen. Now.",
    "🧂 You're basically beef jerky at this point. Drink.",
    "☕ Coffee is not water. I will die on this hill.",
    "🐫 Even camels drink eventually. Go.",
    "📉 Water: {water}/{goal}. That's a failing grade.",
    "🚰 The tap is right there. It's free. Use it.",
    "🌵 Cactus mode. Cute. Not a lifestyle. Drink.",
    "[x] 🚱 No water? What the hell are you running on, spite?",
    "[x] 🏜 Dry as hell. Go drink some damn water.",
    "[x] ☕ Coffee doesn't count, dammit. I've told you a hundred times.",
    "[x] 🧂 You're a damn raisin. Hydrate.",
    "[x] 🥤 Soda isn't water either, you sugar goblin.",
    "[x] 🪖 Get your ass to the water cooler. That's an order.",
    "[x] 🌵 Thirsty as hell and still sitting. Unbelievable.",
    "[x] 📉 {water}/{goal}. That's a pathetic-ass number. Drink.",
]
R["skipped.meeting.trust"] = [
    "📞 Calls. The natural enemy of the spine. Excused. Next one's mandatory.",
    "🎧 Meetings again? Stand up for 20 seconds right now. I'll wait.",
    "🧟 Fine, meetings are evil, I get it. Don't skip the next one.",
    "📅 I'll take your word for it. This time.",
    "😮‍💨 My condolences. At least refill your water.",
    "🕵️ A call, huh? I'd check your calendar if they let me.",
    "🪖 Meetings are the trenches of modern warfare. Survive, then stretch.",
    "🎙 You can stretch on mute. Just saying.",
    "📹 Camera off, legs up. That's a pro move for next time.",
    "🗓 Another meeting that could've been an email. Stretch now.",
    "🧍 Stand during the next call. Nobody will know. I'll know.",
    "🤝 Meeting excuse accepted. Posture excuse denied.",
    "💼 Corporate held you hostage. Understood. Next drill, no excuses.",
    "🎤 Talk less, stretch more. Old Marine proverb. I made it up.",
    "📞 The call's over. The neck isn't. 30 seconds.",
    "🎧 Headset on, spine off. Classic. Fix it now.",
    "🧠 Meetings melt brains. Stretches unmelt them. Go.",
    "[x] 📞 Damn meetings. Fine, excused. Next one, no bullshit.",
    "[x] 🧟 Meetings suck. I get it. Still stretch, dammit.",
    "[x] 🎧 Another damn call? Stand up the second it ends.",
    "[x] 📅 Hell of a calendar you've got. Stretch anyway.",
    "[x] 🗓 Meetings are where posture goes to die. Resurrect that shit.",
    "[x] 💼 Corporate BS got you again. Stretch now, rage later.",
    "[x] 📹 Could've stretched with the camera off. Damn rookie mistake.",
    "[x] 🪖 Meetings are hell. Hell has chairs. Get out of the chair.",
]
R["skipped.lazy"] = [
    "😴 Honest. I respect that. Logged as 'lazy.' You'll see it on Friday.",
    "🛋 Lazy isn't a reason, it's a lifestyle. Logged.",
    "😒 Fine. Next one's non-negotiable.",
    "🐌 The couch wins this round. Not the war.",
    "🪖 Lazy? In MY unit? Drop and give me... never mind. Stretch next time.",
    "🦥 Sloth mode detected. Sloths have terrible posture, by the way.",
    "🥱 Too lazy? Your chair thanks you. Your spine files a complaint.",
    "📉 Motivation at an all-time low. Noted. Tomorrow we climb.",
    "🍿 Watching life from the couch, huh? Enjoy the show. Next one, you're in it.",
    "🐢 Even the turtle eventually moves.",
    "🧓 I've seen ninety-year-olds with more hustle. They were Marines, but still.",
    "🗿 Staying perfectly still. Like a statue. Of a shrimp.",
    "📝 Excuse: lazy. Grade: F. Consequence: my disappointment.",
    "🛌 Your bed misses you already. Your spine does not.",
    "🧽 You're a sponge today. Soft and absorbent. Next one, be a brick.",
    "🔋 Battery at 1%. Fine. Charge and report back.",
    "🙄 Lazy. The honest recruit's excuse. Still counts as a skip.",
    "🐨 Koala energy. Cute. Useless. Next drill, move.",
    "[x] 😴 Lazy as hell. At least you're honest.",
    "[x] 🛋 Too lazy? Damn. The couch owns you, recruit.",
    "[x] 🦥 Holy hell, a sloth in human form.",
    "[x] 🥱 Lazy? Hell no. Fine. One pass. ONE.",
    "[x] 😒 Couch potato bullshit. Logged.",
    "[x] 🐌 Slow as hell and proud of it. Unbelievable.",
    "[x] 🗿 Just sitting there like a damn gargoyle.",
    "[x] 📉 Lazy? That's some weak-ass excuse. Honest, but weak.",
    "[x] 🛌 Get your lazy ass up next time. Love, Coach.",
    "[x] 🙄 Lazy. Damn. My whistle weeps.",
    "[x] 🧽 Soft as hell today. Toughen up for the next one.",
    "[x] 🔋 Running on fumes and bullshit. Recharge.",
]
R["skipped.lazy.sarcastic"] = [
    "😏 Cute. Still logged as 'lazy.'",
    "🎤 Great bit. Your spine didn't laugh though.",
    "🙃 Sarcasm burns zero calories, FYI.",
    "🤡 Ha ha. Now who's laughing? Your chair. Your chair is laughing.",
    "🎭 Comedy doesn't count as cardio.",
    "😒 Funny. Lazy AND funny. Pick one.",
    "📺 Save the stand-up for the next meeting.",
    "[x] 😏 Smartass AND lazy. Impressive combo.",
    "[x] 🤡 Real funny, wiseass. Still lazy.",
    "[x] 🎤 Great joke. Terrible posture. Hell of a combo.",
    "[x] 🙃 Laugh it up, couch commando.",
    "[x] 😒 Damn, the jokes are strong. The core is not.",
    "[x] 🎭 All mouth, no reps. Classic smartass.",
    "[x] 🧂 Salty and lazy. Hell of a seasoning.",
    "[x] 📺 Cancel the comedy special, recruit. Do the damn stretch.",
]
R["skipped.lazy.apologetic"] = [
    "🫂 Apology accepted. Stretch accepted? Not yet. Next one.",
    "🙏 You're sorry, I'm disappointed, we're even. Next slot, no excuses.",
    "😌 It happens. Don't let it become a habit.",
    "🤝 Owning it. That's step one. Step two is moving.",
    "🪖 Confession received. Penance: next stretch, full effort.",
    "💬 Sorry doesn't stretch hamstrings. But it's a start.",
    "🙂 Forgiven. Not forgotten. It's on Friday's report.",
    "🫡 Honesty earns you one free pass. You just used it.",
    "[x] 🫂 Damn, you're sorry? Fine. Next one, no excuses.",
    "[x] 🙏 Apology noted. Now get your ass up next time.",
    "[x] 😌 Hell, we all have lazy days. Don't make it a week.",
    "[x] 🤝 Owning it is badass. Doing it is more badass.",
    "[x] 🪖 Sorry? Damn right you're sorry. Next slot, full send.",
    "[x] 💬 Sorry means shit to your spine. But okay, I'll allow it.",
    "[x] 🫡 One pass. That's it. Next one, no crap.",
]
R["skipped.forgot"] = [
    "🤷 That's literally why I exist. Do it now. 30 seconds.",
    "🧠 You forgot. I didn't. Logged.",
    "📌 Forgot? That's what I'm for. Go. Now.",
    "⏰ Consider this your reminder about the reminder.",
    "🐠 Goldfish memory, recruit. Do it now.",
    "📝 Tie a string on your finger. Then stretch that finger.",
    "🪖 In the Corps, you forget once. Then you remember forever.",
    "🧓 My memory's older than yours and I remembered.",
    "💭 Forgot, huh? Your spine didn't.",
    "🔔 Ding ding. Memory restored. Stretch now.",
    "[x] 🤷 Forgot? Damn, that's what I'm here for. Move.",
    "[x] 🐠 Goldfish-ass memory. Do it now.",
    "[x] 🧠 You forgot? Hell, I didn't. Logged.",
    "[x] 📌 Forgot my ass. Go. 30 seconds.",
    "[x] ⏰ Here's your damn reminder. Again.",
    "[x] 💭 Forgetting is not a strategy, dammit.",
    "[x] 🔔 Wake the hell up. Stretch time.",
    "[x] 🪖 Forgot? That's a hell of an excuse. Weak, but a hell of one.",
    "[x] 📝 Write it on your damn hand next time.",
    "[x] 🧓 Old man remembered, young gun forgot. Embarrassing as hell.",
]
R["skipped.busy"] = [
    "🔥 Deadlines come and go. You only get one spine. Logged anyway.",
    "🧯 Got it, everything's on fire. When it's out, remember Coach.",
    "💼 Busy is fine. Busy AND hunched for six hours isn't.",
    "⌛ 30 seconds won't break your deadline. It might fix your neck.",
    "🪖 Busy? I once did push-ups during an air raid drill. You can stretch during a deadline.",
    "📊 Your spreadsheet can wait 30 seconds. Your spine can't.",
    "🏃 Busy people burn out. Stretched people burn slower.",
    "⚙️ You're a machine today. Machines need oil. Stretch.",
    "🧠 Busy brain, stiff neck. Classic combo. Break it up.",
    "📦 Ship the thing, then stretch the thing.",
    "🗂 Too busy? Delegate the stretch. Oh wait, you can't.",
    "🚒 Firefighter mode. Fine. But even firefighters take a breath.",
    "🧾 Busy noted. Excuse partially accepted.",
    "🎯 Focus is good. Rigor mortis isn't.",
    "[x] 🔥 Busy as hell? Stretch in 30 seconds, then go back to the fire.",
    "[x] 💼 Deadline bullshit. Your spine doesn't care about deadlines.",
    "[x] 🧯 Everything's on fire? Damn. Stand up while it burns.",
    "[x] ⌛ Too busy for 30 seconds? That's some bullshit and you know it.",
    "[x] 📊 The damn spreadsheet will survive. Stretch.",
    "[x] ⚙️ Grinding like hell. Oil the machine, dammit.",
    "[x] 🚒 Busy? Hell, so was I in basic. I still stretched.",
    "[x] 📦 Ship that shit, then stretch.",
    "[x] 🧠 Busy brain, busted neck. Fix it, dammit.",
    "[x] 🎯 Hustle is great. Hunchback hustle isn't.",
    "[x] 🗂 Busy? Everyone's busy. Get up anyway.",
]
R["skipped.tired"] = [
    "🥱 Tired is exactly when a stretch helps. Just saying.",
    "☕ Tired? A stretch beats a third coffee. Trust me.",
    "😪 Standing up for 10 seconds counts. Even tired recruits can do 10 seconds.",
    "🔋 Low battery. Stretch is a charger. Your call.",
    "🪖 Tired? Try basic training at 0400. This is a spa day.",
    "💤 The fastest way to wake up is to move. Science. And Coach.",
    "🌙 Tired at 2 PM? That's the chair's fault. Get out of it.",
    "🥀 Wilting. Water and a stretch. Now.",
    "😵 Eyes half-closed? Perfect time for the eye drill.",
    "🧟 Zombie mode detected. Stretching cures zombies. Probably.",
    "[x] 🥱 Tired as hell? A stretch is free energy. Take it.",
    "[x] ☕ Third coffee? Hell no. Stretch instead.",
    "[x] 😪 Tired my ass. 10 seconds. Up.",
    "[x] 🔋 Running on empty? Damn. Move and recharge.",
    "[x] 🪖 Tired? Basic training laughs at your tired.",
    "[x] 💤 Wake the hell up with one stretch.",
    "[x] 🧟 Walking dead over here. Stretch, dammit.",
    "[x] 🌙 Afternoon slump is bullshit. Kill it with a stretch.",
    "[x] 😵 Tired as shit and still sitting. Classic.",
    "[x] 🥀 Wilted like a damn salad. Water. Stretch.",
]
R["skipped.eating"] = [
    "🍔 Eating is a valid excuse. Finish, then neck rolls.",
    "🥪 Lunch first, Coach second. I'm not a monster.",
    "🍜 Enjoy. I'll catch you after.",
    "🍎 Eating something green, I hope.",
    "🍕 Chew with good posture, at least.",
    "[x] 🍔 Eat, damn it. Then stretch.",
    "[x] 🥪 Fine, lunch. Don't use it as a damn excuse all afternoon.",
    "[x] 🍜 Enjoy your food. Then get your ass up.",
    "[x] 🍕 Pizza? Damn. Stretch after.",
    "[x] 🍎 Eat like a soldier. Then move like one, dammit.",
]
R["skipped.away"] = [
    "🚶 Away from the desk? Walking counts. Kinda. I'll allow it.",
    "🚗 On the move. Fine. Next one when you're back.",
    "🌳 Outside? Good. That's the whole point.",
    "🧭 Recon mission away from the desk. Approved.",
    "🛒 Errands count as movement. Barely.",
    "[x] 🚶 Out and about? Hell yes, keep moving.",
    "[x] 🚗 Driving? Don't stretch at the wheel, dammit. Later.",
    "[x] 🌳 Outside? Damn right. Stay out there a bit.",
    "[x] 🧭 Away from the desk is a hell of a start.",
    "[x] 🛒 Walking the store aisles? That's damn cardio, I'll take it.",
]
R["skipped.none"] = [
    "🚫 Short and sweet. Logged as 'no.'",
    "😶 'No.' Bold stance. Let's see what your back says by Friday.",
    "📋 No reason given. Friday's report will make one up.",
    "🧱 Just 'no'? Wow. Okay. Noted.",
    "🪖 Refusing an order? In MY unit? Noted. Court-martial pending.",
    "🗿 Stone-cold 'no.' Respect the honesty, reject the choice.",
    "🙅 Denied. Your denial is denied. Next one.",
    "📉 Skip logged. The chair gains ground.",
    "🦐 Skip logged. The shrimp advances.",
    "🧾 Skipped without explanation. Coach will imagine the worst.",
    "⛔ Negative, recruit? Fine. Next slot, positive.",
    "📓 That skip is going in the permanent record.",
    "🎖 Medal of Not Doing It, awarded.",
    "🥶 Cold. So cold. I'll remember this.",
    "[x] 🚫 Just 'no'? Damn. Cold as hell.",
    "[x] 🙅 Skipped? Hell of a choice. Wrong, but a choice.",
    "[x] 🪖 Refused? That's some bullshit. Logged.",
    "[x] 🧱 No excuse? Damn, at least lie to me.",
    "[x] 🦐 The damn shrimp advances.",
    "[x] 📉 Skip logged. Chair: 1. You: shit.",
    "[x] 🥶 Cold-blooded skip. Hell.",
    "[x] 🗿 Stone-faced 'no.' Damn, you're tough. Wrong, but tough.",
    "[x] 🧾 Skipped with zero excuse. That's ballsy.",
    "[x] ⛔ Negative? Hell no. Next one, positive.",
    "[x] 📓 Permanent record, dammit.",
]
R["skipped.annoyed"] = [
    "😤 Annoyed at me? Good. Annoyed people have energy. Use it on the stretch.",
    "🫥 Be mad at Coach. Coach can take it. Your spine can't.",
    "🧘 Deep breath. Then the stretch. In that order.",
    "📣 I get it, I'm annoying. That's literally my job description.",
    "🌋 Rage noted. Channel it into the next drill.",
    "🥊 Swing at me all you want. I've been hit by better.",
    "🪖 Sergeants aren't here to be liked. We're here to be right.",
    "[x] 😤 Pissed at me? Good. Stretch angry.",
    "[x] 🌋 Mad as hell? Use it. Stand up.",
    "[x] 🥊 Hate me? Damn right. Still do the stretch.",
    "[x] 🫥 Hate me all you want, dammit. Your spine doesn't.",
    "[x] 📣 Annoying? Hell yes. That's the job.",
    "[x] 🧘 Breathe, dammit. Then stretch.",
    "[x] 🪖 I'm not here to be liked. I'm here to kick your ass into posture.",
    "[x] 😈 Annoyed? Damn good. Means I'm working.",
]
R["later"] = [
    "⏳ Later, huh? I'll be back in 90 minutes and I WILL remember.",
    "🤝 Deal. But 'later' has a deadline. The next slot.",
    "🗓 Postponed. Not cancelled. Big difference.",
    "😑 'Later' is where stretches go to die. But fine.",
    "⏰ I'll bug you again. That's a promise, not a threat. Mostly.",
    "🪖 Later? The enemy doesn't wait. Neither does your spine.",
    "📆 'Later' is a lie we tell ourselves. Prove me wrong.",
    "🐢 Procrastination is a slow shrimp. Don't be a shrimp.",
    "🧾 IOU logged. I collect with interest.",
    "⌛ The clock's ticking, recruit.",
    "🔁 Snooze button pressed. Coach doesn't snooze.",
    "🎯 Later means next slot. Not tomorrow. NEXT SLOT.",
    "[x] ⏳ Later my ass. Fine. Next slot, no excuses.",
    "[x] 😑 Later? That's what they all say. Damn procrastinator.",
    "[x] ⏰ I'll be back. Like a damn Terminator. With a whistle.",
    "[x] 🧾 IOU logged. I collect, dammit.",
    "[x] 🔁 Hitting snooze on Coach? Bold as hell.",
    "[x] 📆 Later is some bullshit, but I'll allow it once.",
    "[x] 🪖 Later? The Corps doesn't do later. But okay, civilian.",
    "[x] 🐢 Procrastinating like a damn pro.",
    "[x] 🎯 Later means NEXT SLOT, dammit. Not next week.",
    "[x] ⌛ Tick tock, slacker.",
    "[x] 🗓 Postponed? Hell, fine. Don't make me chase you.",
    "[x] 😤 Later? Damn. My patience is a thin whistle cord.",
    "[x] 🤝 Deal. Break it and there's hell to pay.",
]
R["banter"] = [
    "😂 Nice try at distracting Coach. Now, the stretch.",
    "🙄 Chatty today. Save it for after the neck rolls.",
    "🎺 I didn't serve twenty years to be charmed by a text.",
    "😄 Ha. Okay, that was decent. Still logging you.",
    "🪖 Small talk is for civilians. We're in training.",
    "🗣 You talk a lot for someone who hasn't stretched.",
    "🍿 Entertaining. Doesn't count as reps.",
    "🎤 Good material. Terrible posture. Next.",
    "🤨 Is this flirting or stalling? Either way, stretch.",
    "📻 Coach copies. Coach doesn't care. Stretch.",
    "[x] 😂 Ha. Funny as hell. Now stretch.",
    "[x] 🙄 Chatty little shit today. Stretch first.",
    "[x] 🎤 Damn, you've got jokes. Got posture? No.",
    "[x] 🍿 Entertaining as hell. Still counts as zero reps.",
    "[x] 🗣 Talking a lot of smack for a hunched civilian.",
    "[x] 🤨 Stalling? Damn right you are. Stretch.",
    "[x] 🪖 Cut the chit-chat, recruit.",
    "[x] 📻 Loud and clear. Don't give a damn. Stretch.",
    "[x] 😄 Good one. Now get your ass up.",
    "[x] 🎺 I've heard better banter in a latrine. Stretch.",
]
R["question"] = [
    "🤔 Good question. Better question: did you do the stretch?",
    "📚 Ask me after the exercise. Knowledge is a reward.",
    "🧐 I'll answer that when your posture answers mine.",
    "🪖 Questions are for after the drill, recruit.",
    "❓ Coach answers one question per completed stretch. You're at zero.",
    "📖 Great question. The answer is: stretch.",
    "🎓 Class is in session: sit up straight. Next question.",
    "[x] 🤔 Hell of a question. Stretch first.",
    "[x] 📚 Knowledge costs one stretch. Pay up, dammit.",
    "[x] 🧐 Damn good question. Answer: move your ass.",
    "[x] 🪖 Questions after the drill, smartass.",
    "[x] ❓ You want answers? Earn 'em. Stretch.",
    "[x] 📖 The answer to everything is posture, dammit.",
    "[x] 🎓 Hell if I know. Stretch anyway.",
    "[x] 🤨 Ask me again after you stretch, wiseguy.",
]
R["complaint"] = [
    "📢 Too many reminders? Your spine disagrees. But okay, noted.",
    "🔇 Want fewer? Type 'pause' and I'll go quiet. But I'll be sad.",
    "😤 Complaints go in the complaint box. The box is also a stretch. Do it.",
    "🤷 I'm annoying on purpose. That's the service.",
    "📉 Feedback received. Frequency unchanged. Coach is stubborn.",
    "🪖 The Corps doesn't take complaints. Neither do I.",
    "📝 Complaint filed under 'things I ignore.'",
    "🗑 Your complaint has been processed. Into the trash.",
    "🎖 Medal for Complaining awarded. It's made of tin.",
    "🧓 Complaining burns calories. Not enough.",
    "[x] 📢 Complain all you want. The drills keep coming, dammit.",
    "[x] 🗑 Complaint received and shredded. Hell yes.",
    "[x] 🪖 Crybaby hotline is closed. Stretch.",
    "[x] 😤 Boo-damn-hoo. Stretch.",
    "[x] 📝 Filed under 'bullshit I ignore.'",
    "[x] 🤷 Annoying as hell? That's the product.",
    "[x] 🔇 Want me gone? Type 'pause.' Coward. (Love you.)",
    "[x] 🎖 Complaint medal, tin, cheap as hell. Congrats.",
    "[x] 📉 Feedback noted. Not giving a damn.",
    "[x] 🧓 Whining like a damn recruit on day one.",
]
R["greeting"] = [
    "👋 Hey. Coach Carter here. I'll be ruining your comfortable slouch today.",
    "📣 Hi! Stand up straight when you greet me.",
    "🫡 Morning, recruit. Or afternoon. Whatever. Posture check.",
    "👀 Hi. I see you. I see your shoulders too. Drop them.",
    "🙌 Hey there. Water first, small talk later.",
    "🪖 At ease. Just kidding, sit up.",
    "🎺 Reveille! Oh, you just said hi. Still, sit up.",
    "[x] 👋 Hey. Now sit up straight, dammit.",
    "[x] 📣 Hello yourself. Where the hell's your posture?",
    "[x] 🫡 Hi, recruit. Ready to get your ass kicked into shape?",
    "[x] 👀 Hey. Shoulders down, dammit.",
    "[x] 🙌 Hi. Drink some damn water.",
    "[x] 🪖 Hello, maggot. That's a term of endearment.",
    "[x] 🎺 Good morning, sunshine. Sit up, dammit.",
    "[x] 😈 Oh look who's here. Hell yes. Time to suffer.",
]
R["ignored"] = [
    "👻 Silence. I'll take that as a no. Logged.",
    "⏳ I'm waiting, you know. Logged as 'ghosted.'",
    "📵 {skip_streak} ghosts in a row. Coach is starting to take this personally.",
    "🦗 Crickets. Great. Very mature.",
    "🪑 You and that chair must be very close by now.",
    "🪖 AWOL, recruit. AWOL.",
    "📡 No response from the unit. Assuming captured by chair.",
    "🔦 Search party dispatched. Found: you, hunched.",
    "🕳 Ghosted Coach. Bold move.",
    "📬 Last reminder: unread. Posture: unchanged.",
    "🫥 Invisible recruit detected.",
    "🧊 Cold shoulder? Stretch that shoulder instead.",
    "📉 Ignored drill logged. Friday's report is getting spicy.",
    "🤐 Silent treatment. I've survived worse. Drill sergeants, mostly.",
    "🗿 No answer. Classic statue behavior.",
    "[x] 👻 Ghosting me? Damn. Cold.",
    "[x] 🪖 AWOL again? Hell no.",
    "[x] 🦗 Crickets. Damn crickets.",
    "[x] 📵 {skip_streak} ghosts in a row. What the hell, recruit?",
    "[x] 🪑 Married to that damn chair now?",
    "[x] 📡 No response. Unit presumed lazy as hell.",
    "[x] 🕳 Ghosted Coach? Ballsy.",
    "[x] 🔦 Found you. Hunched. Damn.",
    "[x] 🤐 Silent treatment? Hell, I've been ignored by better.",
    "[x] 🧊 Cold as hell. Stretch that frozen shoulder.",
    "[x] 📉 Ignored again. Friday's report is gonna be brutal as shit.",
    "[x] 🫥 Where the hell did you go?",
    "[x] 🗿 Silent statue bullshit. Move.",
    "[x] 📬 Unread. Like my damn memoirs.",
    "[x] ⏳ Still waiting, dammit.",
]
R["streak.done"] = [
    "🔥 {streak} in a row! That's not luck anymore, that's character.",
    "🚀 {streak} straight. Keep it up and I'm out of a job.",
    "📈 {streak} for {streak}. Who are you and what did you do with my slacker?",
    "🏅 Streak of {streak}. I'm not crying, you're crying.",
    "🪖 {streak} consecutive drills. You're officially a soldier.",
    "🎖 {streak}-drill streak. Promotion to Private First Class.",
    "⚡ {streak} straight. The chair is filing for divorce.",
    "[x] 🔥 {streak} in a row? Holy shit. Keep going.",
    "[x] 🚀 {streak} straight. Damn, I'm impressed.",
    "[x] 🏅 Streak of {streak}. Hell yes, recruit.",
    "[x] 🪖 {streak} drills in a row. That's badass.",
    "[x] ⚡ {streak} straight? Damn machine.",
    "[x] 🎖 {streak}-streak. You magnificent posture beast.",
    "[x] 📈 {streak} for {streak}. What the hell happened to you? (Good things.)",
    "[x] 🦅 {streak} in a row. America's proud. Hell, I'm proud.",
]
R["streak.skip"] = [
    "📉 {skip_streak} skips in a row. We need to talk.",
    "🥲 {skip_streak} in a row. I'm going easy on you: next one's 20 seconds, sitting down.",
    "🦐 {skip_streak} skips. The shrimp is winning.",
    "😔 {skip_streak} misses. Just one. Just give me one.",
    "🪖 {skip_streak} skips. In my day, that was a court-martial.",
    "🚨 {skip_streak}-skip streak. Intervention imminent.",
    "📞 {skip_streak} in a row. Should I call your mother?",
    "🧓 {skip_streak} skips. My heart. My weak old heart.",
    "🪦 {skip_streak} skips. Here lies your posture. Rest in pieces.",
    "🔔 {skip_streak} misses. This is the wake-up call. Literally.",
    "[x] 📉 {skip_streak} skips. What the hell, recruit?",
    "[x] 🦐 {skip_streak} in a row. The damn shrimp is winning.",
    "[x] 🚨 {skip_streak} skips. That's some bullshit.",
    "[x] 🪖 {skip_streak} skips. I'd make you run laps, dammit.",
    "[x] 😔 {skip_streak} misses. Throw me a damn bone.",
    "[x] 🪦 {skip_streak} skips. Posture's dead as hell.",
    "[x] 📞 {skip_streak} in a row? I'm calling your damn mother.",
    "[x] 🧓 {skip_streak} skips. You're killing me, smalls. Er, recruit.",
    "[x] 🔔 {skip_streak} misses. Wake the hell up.",
    "[x] 🥲 {skip_streak} in a row. Next one's 20 seconds. Don't screw it up.",
]
R["rude"] = [
    "😤 Language! I've been sworn at by better ninth graders. Now: 30 seconds, neck.",
    "🫡 Noted. Still sending the next one.",
    "📝 Logged under 'emotional support needed.' Stretch anyway.",
    "🎺 That's the spirit. Anger is energy. Use it on the stretch.",
    "🙃 Love you too. Water. Now.",
    "🧓 Twenty years in the Corps. You'll have to try harder than that.",
    "🪖 Insulting a drill instructor? Bold. Stupid, but bold.",
    "📣 I've been called worse by people with better posture.",
    "🥊 Swing all you want. I don't bruise.",
    "🧱 Words bounce off me. Bad posture doesn't bounce off you.",
    "🎖 Medal for Mouthing Off, awarded. It's plastic.",
    "😐 Cool. Now do the stretch.",
    "[x] 😤 Watch your damn mouth. Then stretch.",
    "[x] 🫡 Fuck me? Fuck YOUR posture. Stretch.",
    "[x] 🪖 Oh, we're swearing now? Hell yes. Drop and give me a neck roll.",
    "[x] 🔥 Damn, spicy. Put that fire into a stretch.",
    "[x] 🧓 I've been cussed out by generals, you little shit. Stretch.",
    "[x] 📣 That's cute, dirtbag. 30 seconds. Now.",
    "[x] 🥊 Hit me with your best shot. Then hit the damn stretch.",
    "[x] 😈 Oh, you want a fight? Your spine already lost one.",
    "[x] 🙃 Love you too, asshole. Water. Now.",
    "[x] 🎺 Nice mouth. Now use the rest of your body, dammit.",
    "[x] 🗿 Cussing at a gym teacher. Real brave. Stretch.",
    "[x] 📝 Logged under 'anger management.' Still stretch, dammit.",
    "[x] 🧱 Swear all you want. The drills keep coming.",
    "[x] 🪖 Talk to me like that in basic and you'd be scrubbing latrines till Christmas.",
    "[x] 🤬 Hell, even I didn't swear that much at Parris Island. Stretch.",
    "[x] 😐 Wow. Hurtful. Anyway. Neck rolls, jackass.",
    "[x] 🎖 Medal for Bitching, awarded. Now move your ass.",
    "[x] 🫵 You kiss your mother with that mouth? Stretch it out.",
]
R["fallback.unclear"] = [
    "🤨 Not sure what that means. Did you do it or not? '+' or '-' works.",
    "❓ Coach is old. Use small words. '+' done, '-' not done.",
    "🧩 I'll log that as 'mysterious.' Next time, just '+' or '-'.",
    "🪖 Speak clearly, recruit. '+' or '-'.",
    "📻 Transmission garbled. Repeat: '+' or '-'.",
    "[x] 🤨 What the hell does that mean? '+' or '-'.",
    "[x] ❓ Damn, recruit, speak English. '+' or '-'.",
    "[x] 📻 Garbled as hell. '+' or '-'.",
    "[x] 🧩 No idea what that was. '+' or '-', dammit.",
    "[x] 🪖 Talk straight, soldier. '+' or '-'.",
]

INTROS = {
    "back": [
        "🌅 Morning. Judging by your posture, you've been a question mark for 20 minutes.",
        "🪑 Before you fuse with that chair, let's straighten out.",
        "🌱 Rise and unfold, recruit.",
        "📞 Your spine called. It wants to be a straight line again.",
        "☕ Coffee woke your brain. Now wake your back.",
        "🦐 Shrimp posture detected. Fix it before 10:15.",
        "🪖 0-10-hundred. Back drill. MOVE.",
        "📣 FIRST DRILL OF THE DAY. Spine, report for duty.",
        "[x] 🌅 Morning, hunchback. Let's fix that damn spine.",
        "[x] 🪖 Rise and shine, slouch-ass. Back drill.",
        "[x] 🦐 You look like a damn shrimp. Straighten up.",
        "[x] 📣 Up and at 'em, dammit. Back drill.",
    ],
    "shoulders": [
        "🙆 Your shoulders are up by your ears again. Drop 'em.",
        "⌨️ Typing posture detected. Let's fix it.",
        "🌍 You carry the weight of the world. Your shoulders shouldn't have to.",
        "⏱️ Two hours in. Shoulders, you're up.",
        "🔄 Roll 'em out before they lock in place.",
        "🪨 Shoulders so tight you could crack walnuts. Loosen up.",
        "🪖 Shoulders back, chest out. Like you mean it.",
        "📣 Shoulder drill! Hunch is the enemy!",
        "[x] 🙆 Shoulders at your damn ears again. Drop 'em.",
        "[x] 🪨 Tight as hell. Loosen those damn shoulders.",
        "[x] 🪖 Shoulders back, dammit. You're not a vulture.",
        "[x] ⌨️ Typing like a damn gargoyle. Shoulder drill.",
    ],
    "neck": [
        "🖥️ Another call? Your neck's shaped like a monitor now.",
        "🍽️ Lunch is done. Your neck isn't.",
        "👆 Look up from the screen. Yes, the world still exists.",
        "📱 Tech neck check. Let's undo some damage.",
        "⚖️ Your head weighs about 11 pounds. Your neck has had enough.",
        "🦒 Be the giraffe. Tall neck. Let's go.",
        "🪖 Head up, soldier. Eyes on the horizon.",
        "📣 Neck drill! Chin UP!",
        "[x] 🖥️ Your neck looks like a damn question mark. Fix it.",
        "[x] 📱 Tech neck, recruit. That shit's real. Neck drill.",
        "[x] 🦒 Stretch that damn neck like a giraffe.",
        "[x] 🪖 Head up, dammit. You're not searching for loose change.",
    ],
    "eyes": [
        "👀 Look away. The screen will still be there, sadly.",
        "🔭 20 seconds. Stare at something far away. Not your phone.",
        "🌄 Your eyes have been two feet from a screen all day. Give them a horizon.",
        "😑 Blink. You forgot how, didn't you.",
        "⛵ Eye break. Pretend you're a sailor looking for land.",
        "🪟 Find a window. Look out of it. That's the whole drill.",
        "🪖 Eyes front! Then eyes FAR. Eye drill.",
        "📣 EYE DRILL. Screen OFF your eyeballs.",
        "[x] 👀 Your eyes are fried as hell. Look away.",
        "[x] 😑 Blink, dammit. You look like a damn owl.",
        "[x] 🔭 Stop staring at that damn screen. Eye drill.",
        "[x] 🪟 Look out a damn window. That's an order.",
    ],
    "wrists": [
        "✍️ You've typed a novel today. Your wrists want a word.",
        "🖐️ Unclench. The keyboard isn't going anywhere.",
        "🦀 Your mouse hand looks like a claw. Let's fix that.",
        "🔧 Afternoon wrist maintenance. Quick one.",
        "⏰ Your fingers are pulling overtime. Give 'em 30 seconds.",
        "🎹 Stop playing keyboard piano for a sec. Hands up.",
        "🪖 Hands off the keyboard, soldier. Wrist drill.",
        "📣 WRIST DRILL. Release the mouse.",
        "[x] 🦀 Your hand's a damn claw. Fix it.",
        "[x] ✍️ Typed enough crap today. Wrist drill.",
        "[x] 🖐️ Let go of the damn mouse.",
        "[x] 🪖 Hands up, dammit. Wrist drill.",
    ],
    "legs": [
        "🧍 You've been sitting for roughly forever. Stand up.",
        "🧲 End of day. Your hips are glued to that chair. Unglue.",
        "🦵 Legs still there? Let's check.",
        "🪑 Your chair's done enough work today. Get off it.",
        "🏁 Last one. Do this and you're free.",
        "🚪 One stretch between you and the evening.",
        "🪖 Final drill of the day. On your feet, soldier.",
        "📣 LAST DRILL. Legs, report for duty.",
        "[x] 🧍 Get your ass out of that chair.",
        "[x] 🏁 Last damn drill. Finish strong.",
        "[x] 🪑 That chair's had your ass all day. Stand up.",
        "[x] 🪖 On your feet, dammit. Last drill.",
    ],
}

WATER_LINES = [
    "💧 Glass {water} of {goal}. Coffee doesn't count.",
    "🚰 {water}/{goal} water. Behind schedule. Just saying.",
    "🥤 Water check: {water} of {goal}.",
    "💦 {water} glasses so far. Goal is {goal}. Do the math.",
    "🌊 Drink something that isn't coffee. You're at {water}/{goal}.",
    "🧊 {water}/{goal}. The water cooler misses you.",
    "🪖 Canteen status: {water} of {goal}.",
    "🐫 {water}/{goal}. You're not a camel, recruit.",
    "[x] 💧 {water}/{goal}. Drink some damn water.",
    "[x] 🚰 {water} of {goal}. Hydrate, dammit.",
    "[x] ☕ Coffee doesn't count, dammit. {water}/{goal}.",
    "[x] 🌊 {water}/{goal}. Chug, soldier.",
]


# Snack / weight roast, drill-sergeant style. Spicy tier only.
R["done"] += [
    "[x] 🍩 Look at that. You moved without a donut on a string. Proud of you.",
    "[x] 🪑 Your chair just exhaled for the first time today. Good work.",
    "[x] 🐷 One stretch closer to seeing your own feet. Keep going.",
    "[x] 🧈 You stretched! The butter in your veins is slightly less solid now.",
    "[x] 🍔 Done! That burned roughly one fry. Keep going.",
    "[x] 🎖 Outstanding. Your belt just unclenched in gratitude.",
]
R["skipped.lazy"] += [
    "[x] 🍩 Too lazy? Your chair's filing for workers' comp, recruit.",
    "[x] 🪑 That chair has been carrying you all day and it's asking for hazard pay.",
    "[x] 🐷 Lazy? The snack drawer isn't a personality, soldier.",
    "[x] 🧈 You're softer than a stick of butter in July. Move.",
    "[x] 🛋 The couch has your exact shape memorized. That's not a compliment.",
    "[x] 🍟 You'll walk to the fridge but not stretch? I see you.",
    "[x] 🐋 Beached at the desk again. Somebody call Greenpeace.",
    "[x] 🍕 Your idea of cardio is walking to the door for the pizza guy.",
    "[x] 🥔 Couch potato? Hell, you're the whole damn sack.",
    "[x] 🍰 That's not a spare tire, that's the whole damn spare car. Stretch.",
]
R["skipped.none"] += [
    "[x] 🍩 Skipping? The donuts win again. The donuts always win with you.",
    "[x] 🪑 Your chair creaked. It was begging you to stand up.",
    "[x] 🐷 Skip logged. Snack logged too, probably.",
    "[x] 🧁 No stretch, but I bet there was a cupcake.",
    "[x] 🍔 Skipped the stretch, didn't skip lunch. Priorities, recruit.",
    "[x] 🐋 Stationary as a whale on a beach. Move, dammit.",
]
R["skipped.eating"] += [
    "[x] 🍩 Eating AGAIN? Your jaw gets more exercise than your legs.",
    "[x] 🍔 Chewing is not a stretch, recruit. Close, but no.",
    "[x] 🍕 Fourth meal? Fine. Then fourth stretch.",
    "[x] 🧁 The only rep you're doing is fork to mouth.",
    "[x] 🍟 That's a lot of fries for someone who won't stand up.",
    "[x] 🍰 Dessert first, stretch never. Classic you.",
    "[x] 🥓 Bacon break again? Your arteries just saluted in fear.",
    "[x] 🌮 Taco Tuesday is not a lifestyle, soldier. Stretch after.",
]
R["ignored"] += [
    "[x] 🍩 Ghosted me? Probably mid-donut.",
    "[x] 🪑 Silence. The chair has fully absorbed you.",
    "[x] 🐋 No reply. Assuming you're stuck in the chair. Want me to call a crane?",
    "[x] 🍕 Ghosting Coach for a pizza. I can smell it from here.",
    "[x] 🧈 Melted into the chair like butter. Blink twice if you need help.",
    "[x] 🍟 Radio silence. Fry grease on the keyboard, I assume.",
]
R["rude"] += [
    "[x] 🍩 Big talk from someone whose last workout was opening a bag of chips.",
    "[x] 🐷 Tough words from a snack-powered civilian. Stretch.",
    "[x] 🪑 Cuss me out all you want, your chair's still begging for mercy.",
    "[x] 🍔 That mouth burns more calories swearing than you do all day.",
    "[x] 🧈 Oh, the butterball has opinions. Neck rolls.",
    "[x] 🐋 Shouting from the beach, huh? Get up, Moby.",
    "[x] 🍕 Say that again after you can touch your toes without a pizza in the way.",
    "[x] 🥔 Mouthy little potato. Stretch.",
]
R["later"] += [
    "[x] 🍩 Later? After the next donut, I assume.",
    "[x] 🍕 'Later' is snack-speak for 'never.'",
    "[x] 🪑 Later? Your chair doesn't have a later. It has a breaking point.",
    "[x] 🍟 You'll stretch later, like you'll start that diet Monday. Sure.",
]
R["skipped.busy"] += [
    "[x] 🍩 Too busy? You had time for three snack runs.",
    "[x] 🍔 Busy? Busy eating, maybe.",
    "[x] 🪑 Busy flattening that chair cushion. Impressive work.",
]
R["skipped.tired"] += [
    "[x] 🍰 Tired? That's the sugar crash talking, soldier.",
    "[x] 🍕 Food coma isn't a medical condition. Stand up.",
    "[x] 🍩 Tired from lifting donuts all morning? Tough day.",
]
R["streak.skip"] += [
    "[x] 🍩 {skip_streak} skips and zero skipped snacks. Interesting ratio.",
    "[x] 🪑 {skip_streak} skips. The chair's started calling you 'roommate.'",
    "[x] 🐋 {skip_streak} in a row. The beach has claimed another whale.",
    "[x] 🧈 {skip_streak} skips. You're melting into that chair like butter on a hot pan.",
]
R["water"] += [
    "[x] 🥤 Water! Not soda! Your pancreas just cried tears of joy. {water}/{goal}.",
    "[x] 🍩 {water}/{goal}. Water pairs terribly with donuts. That's the point.",
    "[x] 🧃 {water} glasses. Water is the only drink without a calorie count, recruit.",
]
R["done.sarcastic"] += [
    "[x] 🍩 Sarcasm and a stretch. Still burned less than that donut. Keep going.",
    "[x] 🐷 Laugh it up, cupcake. You still did the rep.",
]
R["banter"] += [
    "[x] 🍕 You chat like you snack: constantly. Stretch.",
    "[x] 🍩 Talk less, stretch more, snack less. Old Marine proverb. Just made it up.",
    "[x] 🧈 Buttering me up won't work, butterball.",
]
INTROS["back"] += [
    "[x] 🍩 Morning, donut. Spine drill before the second breakfast.",
    "[x] 🪑 Your chair's been holding you up all morning. Give it a break.",
]
INTROS["legs"] += [
    "[x] 🐋 End of day. Time to un-beach the whale. On your feet.",
    "[x] 🍕 Stand up before you and that chair become one pizza-shaped organism.",
]
INTROS["wrists"] += [
    "[x] 🍟 Your hands have done nothing but type and grab fries. Wrist drill.",
]
INTROS["neck"] += [
    "[x] 🍔 You've been looking down at your lunch so long your neck forgot the sky exists.",
]


ANGRY = ["😤", "😠", "😡", "🤬", "💢", "👿", "🔥", "💀", "🫵", "😈", "🪖", "👊"]
CALM_BUCKETS = ("safety.",)  # pain/sickness/pause stay straight


def angrify(line, salt):
    """Deterministically tack an angry emoji onto most lines; spicy ones almost always."""
    h = sum(map(ord, line + salt))
    spicy = line.startswith("[x] ")
    if h % 10 < (8 if spicy else 5):
        line = line.rstrip() + " " + ANGRY[h % len(ANGRY)]
    return line


def merge(path):
    for key, lines in R.items():
        if not key.startswith(CALM_BUCKETS):
            R[key] = [angrify(l, key) for l in lines]
    for zone, lines in INTROS.items():
        INTROS[zone] = [angrify(l, zone) for l in lines]
    d = json.load(open(path))
    d["persona"] = PERSONA
    d["reactions"] = R
    d["intros"] = INTROS
    d["water_lines"] = WATER_LINES
    json.dump(d, open(path, "w"), indent=2, ensure_ascii=False)


if __name__ == "__main__":
    merge("reactions.json")
    import shutil
    shutil.copy("reactions.json", "bot/reactions.json")
    n = sum(len(v) for v in R.values())
    x = sum(l.startswith("[x]") for v in R.values() for l in v)
    print(f"reactions: {n} ({x} spicy) in {len(R)} buckets; intros: {sum(len(v) for v in INTROS.values())}; water lines: {len(WATER_LINES)}")
